apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnginx2
  labels:
    name: webnginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      apptype: web-backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        apptype: web-backend
    spec:
      containers:
      - name: webnginx2
        image: rithik2005/simplewebapp:latest
        ports:
        - containerPort: 7070
-----------------------------------------------

apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-service
    type: backend-app
spec:
  type: NodePort
  ports:
   - targetPort: 8080
     port: 7070
     nodePort: 30002
  selector:
    apptype: web-backend
